spring:
  datasource:
    url: jdbc:postgresql://localhost:8090/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: airbnb
        format_sql: true
        ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: airbnb.clone.app@gmail.com
    password: xrodvsreyyiikbra
    properties:
      mail:
        smtp:
          auth: true
          enable: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: postgres
    baseline-description: "init"
    baseline-version: 0
    default-schema: airbnb

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000